apiVersion: apps/v1
kind: Deployment
metadata:
  name: channel-learning-session-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channel-learning-session-generator
  template:
    metadata:
      labels:
        app: channel-learning-session-generator
    spec:
      containers:
      - name: channel-learning-session-generator
        image: acralosilla01.azurecr.io/channel-learning-session-generator:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: channel-learning-session-generator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: channel-learning-session-generator